Tin 92 swipe page functionality
Rasmus-Kibshede/TinyTitleTinderClient pull request #10
Opened 2023-11-21 13:55 UTC by Fladbrod

2023-11-22 10:22 UTC, Geofery commented on src/paths/urls.ts
>  export const checkauthPath = `${base}checkauth`;
export const checkAuthPath = `${base}checkauth`;

navngivning - camelCase.

2023-11-22 10:23 UTC, Geofery commented on src/paths/urls.ts
> +// TODO: Make dynamic so that ID is not hardcoded but dependent on the signed in user
Skal det ikke bare ind nu? SignIn er færdig, giver det ikke mening at morgen den ind først og så hurtigt tilføje den functionality her, før vi pusher din branch ind?

2023-11-22 10:26 UTC, Geofery commented on src/ui/components/NameSuggest.tsx
> +                    )}
er det meningen at meanings[0] skal være hardcoded her? Er det altid kun den første meaning vi viser på hvert navn? i så fald, skal vi lave en knap hvor man kan se de andre meanings? Eller er det kun på ReadMore knappen vi kan se det?

2023-11-22 10:27 UTC, Geofery requested changes
Godt arbejde Joachim, har smidt nogle enkelte spørgsmål og forslag til ændringer.

2023-11-23 09:41 UTC, Fladbrod commented
Closing pull request until backend is refactored

2023-11-23 09:41 UTC, closed without merging

2023-11-26 17:33 UTC, Fladbrod commented on src/ui/components/NameSuggest.tsx
> +                    )}
Ja, hvis man vil se mere info så bruger vi read more knappen. Nu er der jo kun en meaning på origin, men vi tager altid det første origin og viser det. Vi kunne godt lave det random, men det ville være rimeligt unødvendigt imo.
Har åbnet et nyt PR.