Tin 81 signup
Rasmus-Kibshede/TinyTitleTinderClient pull request #12
Opened 2023-11-23 11:33 UTC by ThonyDK

2023-11-23 13:10 UTC, Fladbrod requested changes
Der er lige nogle rettelser i kommentarene. Se Swipe branchen for inspiration.

2023-11-23 13:10 UTC, Fladbrod commented on src/ui/pages/Signup.tsx
> +  const validateStringLenght = (value: string, min: number, max: number) => {
Typo
```suggestion
  const validateStringLength = (value: string, min: number, max: number) => {
```

2023-11-23 13:10 UTC, Fladbrod commented on src/ui/pages/Signup.tsx
> +                  error={validateStringLenght(firstname, 2, 40)}
Typo
```suggestion
                  error={validateStringLength(firstname, 2, 40)}
```

2023-11-23 13:10 UTC, Fladbrod commented on src/ui/pages/Signup.tsx
> +                  error={validateStringLenght(lastname, 2, 40)}
Typo
```suggestion
                  error={validateStringLength(lastname, 2, 40)}
```

2023-11-24 11:35 UTC, Geofery commented on src/ui/pages/Signup.tsx
> +          address: address,
er det address object eller er det street?

2023-11-24 23:24 UTC, Fladbrod commented on src/ui/pages/Signup.tsx
> +                  error={!validator.isAscii(address)}
Tror ikke vi skal tjekke for ascii her 🤪

2023-11-25 13:34 UTC, Geofery commented on src/ui/pages/Signup.tsx
> +        console.log("Request sent succesfully!", response.data);
log skal slettes :)

2023-11-25 13:34 UTC, Geofery commented on src/ui/pages/Signup.tsx
> +      console.error("Error, data not send!", error);
log skal slettes :)

2023-12-13 11:20 UTC, Fladbrod approved these changes

2023-12-13 11:20 UTC, merged