created signin with new design format
Rasmus-Kibshede/TinyTitleTinderClient pull request #6
Opened 2023-11-05 17:16 UTC by ThonyDK

2023-11-05 20:19 UTC, Fladbrod requested changes
God arbejde Thony, tænker at vi stadig mangler at få noget baggrunds farve på og et billede af en giraf. 

Vi skal adde følgende i index.html for at kunne bruge Righteous:
<link href="https://fonts.googleapis.com/css2?family=Righteous&display=swap" rel="stylesheet">

Det kan evt skrives sammen med vores roboto font som vi også importere der, ellers kan vi helt fjerne roboto hvis vi ikke bruger den.

2023-11-05 20:19 UTC, Fladbrod commented on src/pages/SignIn.tsx
> +              fontFamily: 'cursive',
You need to import the style from googlefonts in index.html. Also use of fallbacks
```suggestion
              fontFamily: 'Righteous', cursive, sans-serif, 
```

2023-11-08 14:10 UTC, Rasmus-Kibshede commented
Der mangler mere sigende validerings beskeder. Så hvis det ikke er en gyldig email, så skal den sige det og snackbarens placering tænker jeg skal være oppe i toppen og ikke nedre i venstre hjørne :)

Udover det så mangler der hele login logikken, så man kan logge ind :)

Men du er godt på vej :) Hvis signin bliver for stor, så husk at bryd den op i mindre komponenter :)

2023-11-10 11:05 UTC, closed without merging

2023-11-10 11:06 UTC, Geofery commented
Lukket indtil signin virker.