Tin-81.5-signin
Rasmus-Kibshede/TinyTitleTinderClient pull request #9
Opened 2023-11-20 22:48 UTC by Rasmus-Kibshede

Done:
 - Global storage
 - Snackbar
 - login with validation
 - layout
 - setup tailwind with MUI
 - restucture of folder structure

2023-11-21 21:40 UTC, Fladbrod reviewed
Godt arbejde. 
Har skrevet et par kommentarer.

2023-11-21 21:40 UTC, Fladbrod commented on src/ui/components/Layout.tsx
> +    <div id="wrapper" className='bg-[#D6FBE4] h-screen font-main'>
Måske kan vi definere dette i ThemeProvider sammen med andre ting i swipe page functionality branchen.

font-main virker ikke - josefin sans bliver ikke brugt i hverken main app bar eller inputfelter i signup.

2023-11-21 21:40 UTC, Fladbrod commented on src/ui/components/Logout.tsx
> +  useEffect(() => {}, []);
delete
```suggestion

```

2023-11-21 21:40 UTC, Fladbrod commented on tailwind.config.js
> +        tertiary: '#0000ff',
Ville nok definere vores baggrundsfarve mm. her. Primary, secondary og tertiary bliver ikke brugt nogen steder så vidt jeg kan se.
```suggestion
orange: #FFCA80,
green: #D6FBE4,
```

2023-11-21 21:40 UTC, Fladbrod commented on src/routes/AppRouter.tsx
>    }, []);
delete
```suggestion

```

2023-11-21 21:40 UTC, Fladbrod commented on src/ui/pages/SignIn.tsx
> +    const response = await axios.post('http://localhost:3000/login', {
use url
```suggestion
    const response = await axios.post(signin, {
```

2023-11-21 21:40 UTC, Fladbrod commented on src/ui/pages/SignIn.tsx
import login
```suggestion
import { signin } from '../paths/urls';

```

2023-11-22 10:21 UTC, Geofery requested changes
Ser fint ud Rasmus, har smidt nogle få kommentarer. Godt arbejde ellers :)

2023-11-22 10:21 UTC, Geofery commented on src/index.css
> +/* @import url('https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@100&display=swap'); */
Hvorfor er alt det her ukommenteret? Kan vi ikke fjerne det, stedet for det skal op på dev? :)

2023-11-22 10:21 UTC, Geofery commented on src/routes/ProtectedRoute.tsx
>          //Snackbar here when it is on global reach
Er snackbar ikke klar? den står på i pr.

2023-11-22 10:21 UTC, Geofery commented on src/store/user.ts
>  import create from 'zustand';
import { create } from 'zustand';

2023-11-22 10:21 UTC, Geofery commented on src/types/user.ts
> +  roles: Role[] | Role;
roles?: Role[], det er vel altid en liste også selv om der kun er 1 entry?

2023-11-22 13:56 UTC, Rasmus-Kibshede commented
> roles?: Role[], det er vel altid en liste også selv om der kun er 1 entry?  

Nej ikke nødvendigvis, hvorfor have en liste hvis der kun er et element?

2023-11-22 20:50 UTC, Fladbrod approved these changes

2023-11-23 08:00 UTC, Geofery approved these changes
Well done

2023-11-23 08:00 UTC, merged